services:
  web:
    build:
      context: /home/adri/devops/Docker/caronte/
      dockerfile: ./dockerfiles/base/ubbase
      #args: #Variables en DFILE para la construccion (build) de la imagen
      #  - USUARIO=pepe
    container_name: ${CONTAINER_NAME}
    ports:
      - ${PORT_SSH}:${PORT_SSH}
    env_file:
      - ./.env
    #environment:
    # - USUARIO=pepe
    volumes:
      - ./logs:/root/logs
