services:
  web:
    build:
      context: /home/adri/devops/docker/caronte/
      dockerfile: ./dockerfiles/base/ubbase
      #args: #Variables en DFILE para la construccion (build) de la imagen
      #  - USUARIO=pepe
    container_name: ctpbase
    environment:
      - USUARIO=pepe
    volumes:
      - ./logs:/root/logs
