services:
  web:
    build:
      context: /home/adri/devops/Docker/Caronte
      dockerfile: ./Dockerfiles/base/ubbase
      #args: #Variables en DFILE para la construccion (build) de la imagen
      #  - USUARIO=pepe
    container_name: ctpbase
    environment:
      - USUARIO=pepe
      - PASSWORD=1234
    volumes:
      - ./logs:/root/logs
