services:
  web:
    build:
      context: /home/adri/devops/miportfolio/Docker/Caronte
      dockerfile: ./Dockerfiles/base/ubbase
      args: #Variables en DFILE para la construccion (build) de la imagen
        - USUARIO=pepe
    container_name: ctpbase